apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image:v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

          env:
            - name: POSTGRES_HOST
              value: "socialdise-socialdise-123.i.aivencloud.com"
            - name: POSTGRES_PORT
              value: "21244"
            - name: POSTGRES_USER
              value: "avnadmin"
            - name: POSTGRES_PASSWORD
              value: "AVNS_wfp2SlbB4x4NZXcy7MZ"
            - name: POSTGRES_DATABASE
              value: "socialdise"

            - name: CLOUDINARY_CLOUD_NAME
              value: "dnrvpf3j0"
            - name: CLOUDINARY_API_KEY
              value: "818544434872464"
            - name: CLOUDINARY_API_SECRET
              value: "V11pHy7WPm7T-X2D4vbd2TmWxxY"
            - name: SIGHTENGINE_API_USER
              value: "73702169"
            - name: SIGHTENGINE_API_SECRET
              value: "9usQyxFasppmjan3amJkRXEgDj8b5fPC"
            - name: JWT_SECRET
              value: "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"

            - name: POSTGRES_SSL_CA_PATH
              value: "/app/ca.pem"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
